Icon tweak and text changes
blazium-engine/blazium pull request #107
Opened 2024-10-29 19:14 UTC by DeeJayLSP

The icon has been slightly tweaked to play nicer with outlines

The font used for "Blazium" is **Roboto**, with character spacing reduced to -4.0 (in GIMP and Inkscape terms)

The font used for "Game Engine" is **Poppins**.

Most of these changes were based on suggestions by the team in Discord.

2024-10-29 19:18 UTC, sshiiden approved these changes

2024-10-29 19:59 UTC, Norrox approved these changes

2024-10-29 21:36 UTC, jss2a98aj requested changes
I quite like the changes made here. Nice job spotting the previously unchanged VR splash. I only spotted one potential issue

2024-10-29 21:36 UTC, jss2a98aj commented on platform/android/java/lib/res/mipmap-xxxhdpi/icon_foreground.png
This replacement appears to have the old and new version layered on top of each other, at least in the web preview

2024-10-29 21:42 UTC, Norrox commented on platform/android/java/lib/res/mipmap-xxxhdpi/icon_foreground.png
lol, good catch i didn't even see that

2024-10-29 22:23 UTC, DeeJayLSP commented on platform/android/java/lib/res/mipmap-xxxhdpi/icon_foreground.png
Fixed

2024-10-29 22:24 UTC, jss2a98aj submitted a review, later dismissed

2024-10-30 01:24 UTC, Starkium commented
going to need to compare with the other branch that had the revised splash

2024-10-30 02:25 UTC, DeeJayLSP commented
Rebased

2024-10-30 16:56 UTC, DeeJayLSP commented
I have spotted a few oversights in the icon that makes it go out of bounds if placed in a circle. I'll need to rework this PR a bit.

2024-10-30 18:16 UTC, DeeJayLSP commented
Rework finished.

2024-10-30 19:05 UTC, Norrox approved these changes

2024-10-30 19:08 UTC, Norrox commented
> going to need to compare with the other branch that had the revised splash

A little smaller and white text, for me it's fine whichever we choose 
![image](https://github.com/user-attachments/assets/ed52e685-2a16-4b50-be1b-ca8f6e040316)

2024-10-30 19:12 UTC, jss2a98aj submitted a review, later dismissed
Nothing stood out as wrong, and the ico files had the required layers. The recent tweak also seems fine

2024-10-30 19:34 UTC, RandomOfNoWhere approved these changes

2024-10-30 19:57 UTC, Starkium commented
> > going to need to compare with the other branch that had the revised splash
> 
> A little smaller and white text, for me it's fine whichever we choose ![image](https://private-user-images.githubusercontent.com/13393087/381697597-ed52e685-2a16-4b50-be1b-ca8f6e040316.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTg0MDYsIm5iZiI6MTczMDMxODEwNiwicGF0aCI6Ii8xMzM5MzA4Ny8zODE2OTc1OTctZWQ1MmU2ODUtMmExNi00YjUwLWJlMWItY2E4ZjZlMDQwMzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE5NTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzODVlM2EyZTU4M2Y1NDUzYzNhZmMzMTE2NDYzMzg3YzA1NzZlMGMxMzhhNDE2MDZiYjIzNDE3NGRmMWNkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q29SmNgpArvutxs9wm12H91_jbXGoXiODtEpKgPmT18)

maybe we should scale it up? it seems in the other branch they had intentionally scaled it up there

2024-10-30 20:31 UTC, jss2a98aj commented on misc/dist/ios_xcode/godot_ios/Images.xcassets/SplashImage.imageset/splash.png
Was this file supposed to be added?

2024-10-30 20:34 UTC, DeeJayLSP commented on misc/dist/ios_xcode/godot_ios/Images.xcassets/SplashImage.imageset/splash.png
I was dropping the splash there, then using a command to overwrite the others. I ended up forgetting to delete it this time.

2024-10-30 20:45 UTC, jss2a98aj approved these changes

2024-10-31 15:44 UTC, Bioblaze approved these changes

2024-10-31 15:46 UTC, sshiiden approved these changes

2024-10-31 21:58 UTC, merged