Unhardcode and expose doppler effect parameters od audio stream player 3D
blazium-engine/blazium pull request #154
Opened 2024-11-26 23:26 UTC by Limofeus

Adds and exposes 2 parameters to AudioStreamPlayer3D:
doppler_strength - makes doppler effect more / less noticable
doppler_clamp - clamps doppler effect pitch scale between 1/doppler_clamp and doppler_clamp

2024-11-27 00:46 UTC, jss2a98aj submitted a review, later dismissed

2024-11-27 09:22 UTC, Bioblaze commented
Can you run the doc tool, and then push that commit, it should allow for your PR to be merged then :)

2024-11-29 08:37 UTC, Ughuuu approved these changes

2024-11-29 08:38 UTC, Ughuuu commented
Looks good but either ci needs to rerun or code changed to pass ci.

2024-12-01 20:20 UTC, jss2a98aj requested changes
When syncing changes with upstream, please rebase rather than creating a merge commit. The merge commit that was created can be cleaned up with an [interactive rebase as outlined here.](https://docs.blazium.app/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2024-12-03 08:52 UTC, Ughuuu approved these changes

2024-12-04 13:00 UTC, jss2a98aj approved these changes
The two commits should be squshed as outlined in the [PR workflow](https://docs.blazium.app/contributing/workflow/pr_workflow.html#doc-pr-workflow), but changes are otherwise fine.

2024-12-04 14:05 UTC, WhalesState requested changes

2024-12-04 16:51 UTC, Limofeus commented on doc/classes/AudioStreamPlayer3D.xml
> +		</member>
I added rough description, tho I'm not a native English speaker so spellchecking is needed

2024-12-04 17:08 UTC, WhalesState approved these changes

2024-12-04 17:09 UTC, jss2a98aj approved these changes

2024-12-06 05:22 UTC, merged