Typo error in BlaziumClient.xml
blazium-engine/blazium pull request #159
Opened 2024-11-29 14:43 UTC by TheYellowArchitect

2024-11-29 15:00 UTC, Ughuuu approved these changes

2024-11-29 19:00 UTC, Bioblaze commented
@TheYellowArchitect Resolve the conflict sorry~

2024-11-29 21:49 UTC, Ughuuu commented
My bad, did a change that introduced this conflict.

2024-11-29 22:30 UTC, jss2a98aj commented on modules/blazium_sdk/doc_classes/BlaziumClient.xml
> +		An abstract base node used to connect to blazium services.
Blazium should probably be capitalized since there are already changes being made here.

2024-11-29 22:30 UTC, jss2a98aj commented on modules/blazium_sdk/doc_classes/BlaziumClient.xml
> +		An abstract base node used to connect to blazium services. See implementations of it:
Should also be capitalized here.

2024-11-29 22:35 UTC, Ughuuu commented
If it's ok with you @TheYellowArchitect i can make these naming changes, as i work on this anyway. If not you can too

2024-12-07 22:55 UTC, TheYellowArchitect commented
I apologize for the delay, also didn't check emails for many days :sweat_smile: 
For minor PRs like this, I suggest freely overriding code, it's not like anyone would be offended for oneliners

2024-12-07 23:30 UTC, Bioblaze approved these changes

2024-12-08 19:50 UTC, jss2a98aj requested changes
When syncing changes with upstream, please rebase rather than creating a merge commit. The merge commit that was created can be cleaned up with an [interactive rebase as outlined here.](https://docs.blazium.app/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2024-12-11 11:31 UTC, TheYellowArchitect commented
hmmmm, seems I failed the rebase. I checked out at this branch (`patch-2`) then did `git rebase -i blazium-dev` then went to the first commit I did here and replaced the `pick` with `fixup`.

Anyway, feel free to override this PR and close it, its bloated to do rebase or spend more time for typos lol

2024-12-11 11:34 UTC, closed without merging

2024-12-11 16:03 UTC, Ughuuu commented
I'll fix the typo in another PR. Thanks for making this PR and sorry for the merge conflicts.