Drag n Drop new logo
blazium-engine/blazium pull request #212
Opened 2024-12-31 20:28 UTC by sshiiden

Drag n Drop changes from [blazium-assets/pull/37](https://github.com/blazium-engine/blazium-assets/pull/37)

2024-12-31 20:45 UTC, jss2a98aj requested changes
Some tests are failing due to the SVG size being larger than before. It may be possible to optimize the SVGs below the size threshold, but if not a value will need changed in one of the tests.

2024-12-31 20:45 UTC, jss2a98aj commented on platform/android/java/editor/src/meta/assets/vr_splash.png
This file needs to go in `platform/android/java/editor/src/horizonos/assets`, and it probably needs moved in the drag and drop part of the assets repo too. Godot 4.4 and Blazium based on 4.3 (due to backports) both have it in a new location.

2024-12-31 22:20 UTC, sshiiden commented
The PNG splash images went over 60KB

2025-01-07 18:51 UTC, Ughuuu submitted a review, later dismissed

2025-01-07 18:55 UTC, jss2a98aj approved these changes

2025-01-07 19:07 UTC, jss2a98aj commented
Can #123 be addressed here before this is merged if possible?

2025-01-07 22:23 UTC, jss2a98aj submitted a review, later dismissed

2025-01-08 01:05 UTC, jss2a98aj approved these changes

2025-01-08 01:08 UTC, merged