Fix `BottomPanel` excessive width.
blazium-engine/blazium pull request #43
Opened 2024-10-17 11:41 UTC by WhalesState

You can have as many BottomPanel plugins as you want!

https://github.com/user-attachments/assets/3b687255-0aa7-4f34-9ffd-b06789fa3e4c

2024-10-17 13:23 UTC, Murly117 approved these changes

2024-10-17 17:41 UTC, jss2a98aj requested changes
This look like it will be a really nice feature. One of the tooltips should probably be tweaked slightly, but otherwise I did not notice any issues.

2024-10-17 17:41 UTC, jss2a98aj commented on editor/gui/editor_bottom_panel.cpp
> +	left_button->set_tooltip_text(TTR("Scroll Left\nHold Ctrl to scroll to the begin.\nHold Shift to scroll one page."));
"Hold Ctrl to scroll to the begin." should probably be "Hold Ctrl to scroll to the begining." or "Hold Ctrl to scroll to the start."

2024-10-17 18:16 UTC, jss2a98aj approved these changes

2024-10-17 19:34 UTC, Starkium commented
looks like there's a typo
`-	left_button->set_tooltip_text(TTR("Scroll Left\nHold Ctrl to scroll to the begining.\nHold Shift to scroll one page."));
+	left_button->set_tooltip_text(TTR("Scroll Left\nHold Ctrl to scroll to the beginning.\nHold Shift to scroll one page."));`

2024-10-17 19:42 UTC, jss2a98aj commented
> looks like there's a typo
> 
> * left_button->set_tooltip_text(TTR("Scroll Left\nHold Ctrl to scroll to the begining.\nHold Shift to scroll one page."));
> 
> * left_button->set_tooltip_text(TTR("Scroll Left\nHold Ctrl to scroll to the beginning.\nHold Shift to scroll one page."));

That typo was my fault, I had it messed up when suggesting a change.

2024-10-17 20:38 UTC, Starkium commented
someone stopped the tests. I'll rerun this again once those are done

2024-10-17 20:42 UTC, jss2a98aj commented
> someone stopped the tests. I'll rerun this again once those are done

Those stopped automatically when the static check failed from the typo.

2024-10-18 02:22 UTC, Starkium commented on editor/gui/editor_bottom_panel.cpp
> +	left_button->set_tooltip_text(TTR("Scroll Left\nHold Ctrl to scroll to the begining.\nHold Shift to scroll one page."));
spell check linter "beginning"

2024-10-18 03:22 UTC, jss2a98aj approved these changes

2024-10-18 03:25 UTC, merged